#!/usr/bin/env bash
set -euo pipefail
repo="$(cd "$(dirname "$0")/.." && pwd)"
box="$repo/boxes/megarac-hpe"

grep -Fq 'qemu/runtime/qemu-system-arm' "$box/zbmc.box"
grep -Fxq 'ZBMC_QEMU_SHA256=a066ffd52f50bc4555ea9af003e44e02aec3b3d260a37da8ab0b3d8c596790a6' "$box/zbmc.box"
grep -Fxq 'ZBMC_QEMU_MAJOR=11' "$box/zbmc.box"
grep -Fxq 'ZBMC_QEMU_MACHINE=ast2600-evb' "$box/zbmc.box"
grep -Fxq 'ZBMC_REQUIRED_SERVICES="ipmi redfish webui"' "$box/zbmc.box"
grep -Fxq 'ZBMC_STABILITY_SECONDS=60' "$box/zbmc.box"
grep -Fq 'IPMI, Redfish, and Web-UI login; vendor SSH absent' "$box/zbmc.box"
grep -Fxq 'ZBMC_WARM_STATUS=broken' "$box/zbmc.box"
grep -Fq 'saved ASPEED SRAM is 0x17000; current model requires 0x18000' "$box/zbmc.box"
grep -Fq 'Never expose this guest outside an isolated lab' "$box/zbmc.box"
grep -Fq 'ZBMC_INSECURE_LAB_ACCESS=1 for isolated-lab access' "$box/zbmc.box"
grep -Fq '[ "${ZBMC_INSECURE_LAB_ACCESS:-0}" != 1 ] || HOSTFWD=' "$box/boot-megarac-hpe-svc.sh"
grep -Fq 'if [ -n "${ZBMC_WARM:-}" ]' "$box/zbmc.box"
for script in boot.sh boot-megarac-hpe.sh boot-megarac-hpe-svc.sh restore-megarac-hpe.sh; do
  grep -Fq 'QEMU_BIN="${ZBMC_QEMU:-${QEMU:-qemu-system-arm}}"' "$box/$script"
done
grep -Fq "IPMIMain is terminating because of SIGSEGV" "$box/start-megarac-hpe-green.sh"
grep -Fq 'python3 -m zipmi.cli.zipmi' "$box/start-megarac-hpe-green.sh"
grep -Fq 'waiting for authenticated IPMI' "$box/start-megarac-hpe-green.sh"
grep -Fq 'trap cleanup EXIT' "$box/start-megarac-hpe-green.sh"
grep -Fq "trap 'exit 130' HUP INT TERM" "$box/start-megarac-hpe-green.sh"
grep -Fq '[ -n "$qp" ] && ps -p "$qp" >/dev/null 2>&1' "$box/start-megarac-hpe-green.sh"
! grep -Fq 'ipmimain_keepalived' "$box/qemu-patch-rootfs.sh"
! grep -Fq 'touch /var/tmp/rc-init-complete' "$box/qemu-patch-rootfs.sh"
! grep -Fq 'SUPPORT_KCS1_IFC=)1/\10/' "$box/qemu-patch-rootfs.sh"
! grep -Fq 'SUPPORT_KCS2_IFC=)1/\10/' "$box/qemu-patch-rootfs.sh"
! grep -Fq 'SUPPORT_KCS3_IFC=)1/\10/' "$box/qemu-patch-rootfs.sh"
! grep -Fq 'IPMIMain --daemonize --reg-with-procmgr >/dev/null 2>&1' "$box/qemu-patch-rootfs.sh"
grep -Fq 'FWINFO_OFF=$((0x3EF028F))' "$box/build-from-hpm.sh"
grep -Fq "assert b'FW_CODEBASEVERSION=5.X\\n' in fwinfo" "$box/build-from-hpm.sh"
grep -Fq 'fdtput -t s dtb-a1.dtb "$parts" compatible fixed-partitions' "$box/build-from-hpm.sh"
grep -Fq '"100000 conf 100000 200000"' "$box/build-from-hpm.sh"
grep -Fq '"a00000 root a00000 3600000"' "$box/build-from-hpm.sh"
grep -Fq 'chmod u+x rootfs/etc/defconfig/crontabs' "$box/build-from-hpm.sh"
grep -Fq '"$(size "$WD/$f")"' "$box/build-from-hpm.sh"
grep -Fq 'BUILD_EPOCH=1775804692' "$box/build-from-hpm.sh"
grep -Fq 'FW_SHA256=4e85590c2d5f18caf670b916522555347173ac277b098713c889303a7630cb76' "$box/build-from-hpm.sh"
grep -Fq '[ "$(sha "$FW")" = "$FW_SHA256" ]' "$box/build-from-hpm.sh"
grep -Fq 'find rootfs -newermt "@$BUILD_EPOCH"' "$box/build-from-hpm.sh"
grep -Fq -- '-mkfs-time "$BUILD_EPOCH"' "$box/build-from-hpm.sh"
! grep -Fq 'start-megarac-hpe-green.sh" >>"$LOG" 2>&1' "$box/zbmc.box"
grep -Fq 'start-megarac-hpe-green.sh" >/dev/null || return 1' "$box/zbmc.box"
grep -Fq 'zbmc_redfish_health()' "$box/zbmc.box"
grep -Fq '/redfish/v1/Managers' "$box/zbmc.box"
grep -Fq 'zbmc_webui_health()' "$box/zbmc.box"
grep -Fq '/api/settings/dashboardinfo' "$box/zbmc.box"
! grep -Fq 'redfish/v1/' "$box/start-megarac-hpe-green.sh"
grep -Fq 'dtb-a1.dtb:57699dc066fd995075f234acd9b489461bda28a9e6f91b6b275363cb338b5939' "$box/build.sh"
grep -Fq 'rootfs.sqfs:d757b2ee0654c7a125e24316d2cfcb05f5919d0962a6901f71f1f0a9a9239b62' "$box/build.sh"
grep -Fq 'mtdflash.bin:d64412d0d0c13fc6bb03f52ea35bedf8762919a5c069c51a808e5e374b8e252e' "$box/build.sh"
! grep -Fq 'cray-snap.gz:' "$box/build.sh"

echo "MegaRAC-HPE QEMU contract: PASS"
